# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-docker-config"
BBFILE_PATTERN_meta-docker-config = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-docker-config = "6"

LAYERDEPENDS_meta-docker-config = "core"
LAYERSERIES_COMPAT_meta-docker-config = "scarthgap"
